### PR TITLE
MODEST REDUCTIONS IN CPU / MEMORY CONSUMPTION

### PR DESCRIPTION
**Pull request by BourgeoisBear**
- constant pre-calc for Distorter.ComputeFrame to reduce redundant calc
- moved some calculations out of inner loop that didn't need to be there in RomGraphics.drawTile
- reduced superfluous bitmap allocation in BackgroundLayer
- replaced timestamp-based spinlocks with setTimeout() for fps throttling requestAnimationFrame()
- OO style for Engine/EB_Animator to persist reusables between settings changes

P.S.> Left some junk in index.html.  index.html can be reverted.

### CODE REVIEW

**Comment by ghost** [comment]
@BourgeoisBear I've added some of your changes to my [actively maintained repository](https://github.com/kdex/earthbound-battle-backgrounds). Some of which turned out to be drastically changing the rendering, which is why I couldn't accept them.

I'm not sure how actively @gjtorikian maintains this repository still (e. g. note that the last commit that wasn't about `gh-pages` was from about two years ago). I've also worked my way through the code and reduced CPU/memory consumption by about 20% and gave this project a proper ES2015 re-write.

**Comment by BourgeoisBear** [comment]
Kdex,

Which parts changed rendering, so I can undo?

Thx.

JS

**Comment by gjtorikian** [comment]
I still do actively watch / maintain this repo. I think I just forgot about this PR because of the proximity to the new year. 

I think if the changes in index.html could be reverted most everything else looks clean.

**Comment by BourgeoisBear** [comment]
They can.  I forgot to revert index.html before I pushed.  Sorry!

JS

**Comment by ghost** [comment]
@BourgeoisBear It's been a while since I've last looked at your diff, but IIRC, your change:

> - moved some calculations out of inner loop that didn't need to be there in `RomGraphics.drawTile`

isn't equivalent to whatever the renderer does upstream (i. e. I have noticed a notably different rendering); at least it caused a notable change for some `BackgroundLayer`s for me, that is.

As for the other points you've listed, I'm not sure anymore (I'll be able to check in April).

**Comment by ghost** [comment]
@gjtorikian I wouldn't want to create pull requests for every little change that I did, especially since my files will require transpilation (at least as of today), so most of which couldn't be merged without drastic changes to this code anyway. Other than that, [this](https://github.com/kdex/earthbound-battle-backgrounds#how-does-this-port-differ) should give a good summary of what has been done so far.

The most visible/notable change is probably removing the computation overhead when changing the background layers at runtime (your renderer turns white for some time. IIRC, this required a new implementation of the renderer and the ability to have only one single ROM instance at runtime. The files [readBackgroundData.js](https://github.com/kdex/earthbound-battle-backgrounds/blob/master/src/readBackgroundData.js) and [Engine.js](https://github.com/kdex/earthbound-battle-backgrounds/blob/master/src/Engine.js) should probably summarize the way it should be handled here as well.

If you want to see the difference, try changing the background layers [here](https://github.kdex.de/earthbound-battle-backgrounds/) with `[+]` and `[-]`  for layer 1 (hold `[Shift]` for layer 2).

**Comment by gjtorikian** [comment]
@kdex What I love most about your changes are that you managed to get the whole thing fullscreen, which is something I simply never investigated. That's pretty awesome!

As should probably be clear, for me this was an experiment to get the code rendering in Javascript. Maybe by the time ES7 rolls around I'll take a look at cleaning it up. :grin:

**Comment by ghost** [comment]
@gjtorikian Thanks so much! By the way, a simple thing to do right away would be to remove `src/romlib/romObject.js` (I didn't see it used anywhere); I think this is an old relic from the Java codebase (which is where I saw it used). :smile:

There's still some big stuff I'd love to tackle this year, especially:
- re-work the math so it works on the truncated data without artificially padding it
- use WebGL for hardware-accelerated rendering

but speaking of the former, I would have two questions:
- Do you happen to still have the old C# codebase (and if so, could I have a little peek at it)?
- Was the truncated binary in the original C# code, too? Or did you create that for the web to optimize loading time?

**Comment by gjtorikian** [comment]
> Do you happen to still have the old C# codebase

Yeah! I dug up the zip file I received from _five years ago_ and have tossed it here: https://github.com/gjtorikian/kraken

> Was the truncated binary in the original C# code, too?

Yep. It wasn't considered for optimization at all. The original C# code just _knew_ the offset of where the background data was at.

**Comment by ghost** [comment]
Much obliged! Will definitely give it a look!

**Comment by ghost** [comment]
@BourgeoisBear I've found some time to further look into and review your changes. First of all, sorry for the noise before; it seems that your changes in `RomGraphics.drawTile` are fine (as I couldn't spot any visual differences when I re-implemented your changes for a second time).

I've made some modifications to your changes. They've landed [here](https://github.com/kdex/earthbound-battle-backgrounds/commit/3895836fe1635336423181b212201503f2915365) and [here](https://github.com/kdex/earthbound-battle-backgrounds/commit/700af4b0a4234be54bbcdb289ec1760afeacb192).

I'm still not sold about your changes in `engine.js` though, as I've measured a negative performance change compared to my baseline. But maybe I've just made a mistake when applying your changes.

I will investigate this further.

So, other than that and accidental changes in `index.html`, this PR looks good to me.

**Comment by BourgeoisBear** [comment]
I'm not sure what the change was, but if I remember correctly, I used
setTimeout() instead of timestamp math to throttle FPS below the threshold
set by requestAnimationFrame(). It wasn't a performance tweak (no
appreciable gain or loss in CPU usage on my side). It was done purely for
legibility, so no strong feelings about whether it is kept or discarded.

Thx.

JS

**Comment by ghost** [comment]
Here's some investigation about performance changes regarding this PR. I've performed measurements on three different implementations:
- **[Implementation 1](https://github.com/gjtorikian/Earthbound-Battle-Backgrounds-JS/commit/a82659ddf7a893cc46c2ba05ddf310d32ca21a17) ([gjtorikian](https://github.com/gjtorikian/Earthbound-Battle-Backgrounds-JS), before merging this PR)** (Heap allocations: **32.7 MiB**)
- **[Implementation 2](https://github.com/kdex/earthbound-battle-backgrounds/commit/b2a22cb3d9088ef56afaaba8b96cff80c899e621) ([kdex](https://github.com/kdex/earthbound-battle-backgrounds), before merging this PR)** (Heap allocations: **25.5 MiB**)
- **[Implementation 3](https://github.com/kdex/earthbound-battle-backgrounds/commit/700af4b0a4234be54bbcdb289ec1760afeacb192) ([kdex](https://github.com/kdex/earthbound-battle-backgrounds), after partially\* merging this PR)** (Heap allocations: **24.5 MiB**)

*_partially_: All changes except for those in `engine.js`

## CPU profile (over 5 seconds)

### Implementation 1

Implementation 1, chart
Especially note the broad blue spikes at the top; these indicate code execution (and thus blocking code). Especially in games/rendering, you want to keep these as narrow as you can (as users will notice if these spikes become too broad by the page starting to lag). (The height of a spike is the call depth, if I'm not mistaken.)

### Implementation 2

Implementation 2, chart
The page has a lot more time to do other stuff than rendering now. You'll see that the spikes are thinner. (Don't mind that I've increased the call depth by one call.)

### Implementation 3

Implementation 3, chart
This looks slightly better, except for the end (after 4 seconds, some calls tend to block more often). I'm not sure what causes that, yet. (Edit: Also, they're pretty hard to reproduce for me. Probably just cosmic rays interfering with my CPU :smile:) Note that the spikes aren't as high as before, as call depths are sometimes smaller now.

## CPU profile (first second)

### Implementation 1

Implementation 1, 1 second
Have a look at the bottom; this is a magnified view over what you see on the top. This makes it possible to see how long each call or their sub-calls take.

### Implementation 2

Implementation 2, 1 second
The bars are more narrow, just like in the five-second comparison.

### Implementation 3

Implementation 3, 1 second
Note that here, the bars are not only more narrow than in implementation 2, but there's fewer sub-calls of order 4 (the gray rectangles at the bottom). This is an internal optimization from the pull request and results in the bars being shorter. Nice job.

## CPU profile (over 5 seconds, tabular)

### Implementation 1

Implementation 1, table
Out of a five-second measurement, the idle time was about **73.48 %**.

### Implementation 2

Implementation 2, table
Out of a five-second measurement, the idle time was about **81.58 %**.

### Implementation 3

Implementation 3, table
Out of a five-second measurement, the idle time was about **84.61 %**.

## Results

So, with all the optimizations from implementation 1 to implementation 3, we have
- **33.5% less memory used**
- **15.2% more idle time**
- **23.0% less time spent in `computeFrame()`**
- **`romGraphics.drawTile()` is more than twice as fast**
- and a lot more bonuses, if you take a look at the measurements

**Comment by gjtorikian** [comment]
@kdex Would you be interested in porting some of the improvements in your fork into this repository? I can grant you collaborator access if needed. 

When I started this project, Babel and ES6 didn't exist yet. I really like the improvements you've been making and frankly look forward to learning more from your code.

**Comment by ghost** [comment]
@gjtorikian I'm not sure; even using the smallest of my improvements would require me to touch/replace **every single file** in this repository (:frowning:), as RequireJS has been dropped as a result of my changes towards ES2015 module transformation/code transpilation.

Also, my repository isn't a fork per-se; though it _is_ based on your code. The goals are seemingly different, however:

My implementation was created to serve the purpose of using the backgrounds in canvas-based applications (e. g. games) with some sort of programmatic API (which is what I've been working on for some time now and will be up soon).

This original implementation, at least to me, serves the purpose of offering a neat, little GUI to display all different layer combinations in a browser. This is why Node Express and the GUI aren't part of my repository either.

Note that the biggest improvement, in terms of performance, was the ES2015+ rewrite, i. e. I'd **have to** rewrite every single file for the biggest chunk of performance boost. What do you suggest?

**Comment by ghost** [comment]
@gjtorikian One idea could be to separate the code for presenting the layers in browsers from the actual rendering engine (i. e. once I implement the programmatic API, you could make this repository rely on my re-worked engine which I will keep optimizing).

This way, there would be no hassle with merging anything and we'd even get a neat abstraction layer for free (rendering engine vs. app that uses the engine as a black box). What do you think?

**Pull request merged**
